// Typed models for the Vercel SDK (JSDoc typedefs).
//
// GENERATED from the API model: main.kit.entity.<e>.fields[] and per-op
// params (op.<name>.points[].args.params[]). Field/param types come from the
// canonical type sentinels via @voxgig/sdkgen canonToType (source of truth:
// @voxgig/apidef VALID_CANON). Annotations only — no runtime effect. Do not
// edit by hand.

/**
 * @typedef {Object} Project
 * @property {Object} abuse
 * @property {string} accountId
 * @property {Array} alias
 * @property {Object} analytics
 * @property {boolean} [appliedCve55182Migration]
 * @property {boolean} [autoAssignCustomDomains]
 * @property {string} [autoAssignCustomDomainsUpdatedBy]
 * @property {boolean} [autoExposeSystemEnvs]
 * @property {string} [avatar]
 * @property {Object} [blobs]
 * @property {string} [buildCommand]
 * @property {string} [commandForIgnoringBuildStep]
 * @property {string} [concurrencyBucketName]
 * @property {boolean} [connectBuildsEnabled]
 * @property {string} [connectConfigurationId]
 * @property {Array} [connectConfigurations]
 * @property {number} [createdAt]
 * @property {*} [creator]
 * @property {Object} crons
 * @property {Array} [customEnvironments]
 * @property {boolean} [customerSupportCodeVisibility]
 * @property {Object} dataCache
 * @property {Object} defaultResourceConfig
 * @property {Object} deploymentExpiration
 * @property {Object} [deploymentPolicy]
 * @property {string} [devCommand]
 * @property {boolean} directoryListing
 * @property {Array} [dismissedToasts]
 * @property {boolean} [enableAffectedProjectsDeployments]
 * @property {boolean} [enableExternalRewriteCaching]
 * @property {boolean} [enablePreviewFeedback]
 * @property {boolean} [enableProductionFeedback]
 * @property {Array} [env]
 * @property {Array} [environmentVariables]
 * @property {*} [expiration]
 * @property {Object} [features]
 * @property {string} [framework]
 * @property {Object} gitComments
 * @property {boolean} [gitForkProtection]
 * @property {boolean} [gitLFS]
 * @property {Object} gitProviderOptions
 * @property {Object} gitRepository
 * @property {boolean} [hasActiveBranches]
 * @property {boolean} [hasDeployments]
 * @property {string} id
 * @property {string} [installCommand]
 * @property {Array} [integrations]
 * @property {Array} [internalRoutes]
 * @property {Array} [ipBuckets]
 * @property {Object} [jobs]
 * @property {Object} lastAliasRequest
 * @property {Object} [lastRollbackTarget]
 * @property {Array} [latestDeployments]
 * @property {string} [link]
 * @property {boolean} [live]
 * @property {*} [microfrontends]
 * @property {string} name
 * @property {string} nodeVersion
 * @property {Object} [oidcTokenConfig]
 * @property {Object} optionsAllowlist
 * @property {string} [outputDirectory]
 * @property {string} [passiveConnectConfigurationId]
 * @property {Object} passport
 * @property {Object} [passwordProtection]
 * @property {boolean} [paused]
 * @property {Object} [permissions]
 * @property {string} [previewDeploymentSuffix]
 * @property {boolean} [previewDeploymentsDisabled]
 * @property {boolean} [productionDeploymentsFastLane]
 * @property {boolean} [protectedSourcemaps]
 * @property {Object} [protectionBypass]
 * @property {Object} [protectionConfig]
 * @property {boolean} [publicSource]
 * @property {Object} resourceConfig
 * @property {Object} rollbackDescription
 * @property {Object} rollingRelease
 * @property {string} [rootDirectory]
 * @property {Object} [sandbox]
 * @property {Object} [security]
 * @property {string} [serverlessFunctionRegion]
 * @property {boolean} [serverlessFunctionZeroConfigFailover]
 * @property {Array} [services]
 * @property {Array} [skewProtectionAllowedDomains]
 * @property {number} [skewProtectionBoundaryAt]
 * @property {number} [skewProtectionMaxAge]
 * @property {boolean} [skipGitConnectDuringLink]
 * @property {boolean} [sourceFilesOutsideRootDirectory]
 * @property {Object} speedInsights
 * @property {Object} ssoProtection
 * @property {Object} staticIps
 * @property {Object} [targets]
 * @property {string} [tier]
 * @property {Object} [tracing]
 * @property {number} [transferCompletedAt]
 * @property {number} [transferStartedAt]
 * @property {string} [transferToAccountId]
 * @property {string} [transferredFromAccountId]
 * @property {*} [trustedIps]
 * @property {Object} [trustedSources]
 * @property {number} [updatedAt]
 * @property {Object} usageStatus
 * @property {boolean} [v0]
 * @property {boolean} [v0Created]
 * @property {Object} webAnalytics
 */

/**
 * @typedef {Object} ProjectLoadMatch
 * @property {string} id
 * @property {string} [slug]
 * @property {string} [team_id]
 */

/**
 * @typedef {Object} ProjectCreateData
 * @property {string} [slug]
 * @property {string} [team_id]
 * @property {Object} abuse
 * @property {string} accountId
 * @property {Array} alias
 * @property {Object} analytics
 * @property {boolean} [appliedCve55182Migration]
 * @property {boolean} [autoAssignCustomDomains]
 * @property {string} [autoAssignCustomDomainsUpdatedBy]
 * @property {boolean} [autoExposeSystemEnvs]
 * @property {string} [avatar]
 * @property {Object} [blobs]
 * @property {string} [buildCommand]
 * @property {string} [commandForIgnoringBuildStep]
 * @property {string} [concurrencyBucketName]
 * @property {boolean} [connectBuildsEnabled]
 * @property {string} [connectConfigurationId]
 * @property {Array} [connectConfigurations]
 * @property {number} [createdAt]
 * @property {*} [creator]
 * @property {Object} crons
 * @property {Array} [customEnvironments]
 * @property {boolean} [customerSupportCodeVisibility]
 * @property {Object} dataCache
 * @property {Object} defaultResourceConfig
 * @property {Object} deploymentExpiration
 * @property {Object} [deploymentPolicy]
 * @property {string} [devCommand]
 * @property {boolean} directoryListing
 * @property {Array} [dismissedToasts]
 * @property {boolean} [enableAffectedProjectsDeployments]
 * @property {boolean} [enableExternalRewriteCaching]
 * @property {boolean} [enablePreviewFeedback]
 * @property {boolean} [enableProductionFeedback]
 * @property {Array} [env]
 * @property {Array} [environmentVariables]
 * @property {*} [expiration]
 * @property {Object} [features]
 * @property {string} [framework]
 * @property {Object} gitComments
 * @property {boolean} [gitForkProtection]
 * @property {boolean} [gitLFS]
 * @property {Object} gitProviderOptions
 * @property {Object} gitRepository
 * @property {boolean} [hasActiveBranches]
 * @property {boolean} [hasDeployments]
 * @property {string} id
 * @property {string} [installCommand]
 * @property {Array} [integrations]
 * @property {Array} [internalRoutes]
 * @property {Array} [ipBuckets]
 * @property {Object} [jobs]
 * @property {Object} lastAliasRequest
 * @property {Object} [lastRollbackTarget]
 * @property {Array} [latestDeployments]
 * @property {string} [link]
 * @property {boolean} [live]
 * @property {*} [microfrontends]
 * @property {string} name
 * @property {string} nodeVersion
 * @property {Object} [oidcTokenConfig]
 * @property {Object} optionsAllowlist
 * @property {string} [outputDirectory]
 * @property {string} [passiveConnectConfigurationId]
 * @property {Object} passport
 * @property {Object} [passwordProtection]
 * @property {boolean} [paused]
 * @property {Object} [permissions]
 * @property {string} [previewDeploymentSuffix]
 * @property {boolean} [previewDeploymentsDisabled]
 * @property {boolean} [productionDeploymentsFastLane]
 * @property {boolean} [protectedSourcemaps]
 * @property {Object} [protectionBypass]
 * @property {Object} [protectionConfig]
 * @property {boolean} [publicSource]
 * @property {Object} resourceConfig
 * @property {Object} rollbackDescription
 * @property {Object} rollingRelease
 * @property {string} [rootDirectory]
 * @property {Object} [sandbox]
 * @property {Object} [security]
 * @property {string} [serverlessFunctionRegion]
 * @property {boolean} [serverlessFunctionZeroConfigFailover]
 * @property {Array} [services]
 * @property {Array} [skewProtectionAllowedDomains]
 * @property {number} [skewProtectionBoundaryAt]
 * @property {number} [skewProtectionMaxAge]
 * @property {boolean} [skipGitConnectDuringLink]
 * @property {boolean} [sourceFilesOutsideRootDirectory]
 * @property {Object} speedInsights
 * @property {Object} ssoProtection
 * @property {Object} staticIps
 * @property {Object} [targets]
 * @property {string} [tier]
 * @property {Object} [tracing]
 * @property {number} [transferCompletedAt]
 * @property {number} [transferStartedAt]
 * @property {string} [transferToAccountId]
 * @property {string} [transferredFromAccountId]
 * @property {*} [trustedIps]
 * @property {Object} [trustedSources]
 * @property {number} [updatedAt]
 * @property {Object} usageStatus
 * @property {boolean} [v0]
 * @property {boolean} [v0Created]
 * @property {Object} webAnalytics
 */

/**
 * @typedef {Object} ProjectUpdateData
 * @property {string} id
 * @property {string} [slug]
 * @property {string} [team_id]
 * @property {Object} [abuse]
 * @property {string} [accountId]
 * @property {Array} [alias]
 * @property {Object} [analytics]
 * @property {boolean} [appliedCve55182Migration]
 * @property {boolean} [autoAssignCustomDomains]
 * @property {string} [autoAssignCustomDomainsUpdatedBy]
 * @property {boolean} [autoExposeSystemEnvs]
 * @property {string} [avatar]
 * @property {Object} [blobs]
 * @property {string} [buildCommand]
 * @property {string} [commandForIgnoringBuildStep]
 * @property {string} [concurrencyBucketName]
 * @property {boolean} [connectBuildsEnabled]
 * @property {string} [connectConfigurationId]
 * @property {Array} [connectConfigurations]
 * @property {number} [createdAt]
 * @property {*} [creator]
 * @property {Object} [crons]
 * @property {Array} [customEnvironments]
 * @property {boolean} [customerSupportCodeVisibility]
 * @property {Object} [dataCache]
 * @property {Object} [defaultResourceConfig]
 * @property {Object} [deploymentExpiration]
 * @property {Object} [deploymentPolicy]
 * @property {string} [devCommand]
 * @property {boolean} [directoryListing]
 * @property {Array} [dismissedToasts]
 * @property {boolean} [enableAffectedProjectsDeployments]
 * @property {boolean} [enableExternalRewriteCaching]
 * @property {boolean} [enablePreviewFeedback]
 * @property {boolean} [enableProductionFeedback]
 * @property {Array} [env]
 * @property {Array} [environmentVariables]
 * @property {*} [expiration]
 * @property {Object} [features]
 * @property {string} [framework]
 * @property {Object} [gitComments]
 * @property {boolean} [gitForkProtection]
 * @property {boolean} [gitLFS]
 * @property {Object} [gitProviderOptions]
 * @property {Object} [gitRepository]
 * @property {boolean} [hasActiveBranches]
 * @property {boolean} [hasDeployments]
 * @property {string} [installCommand]
 * @property {Array} [integrations]
 * @property {Array} [internalRoutes]
 * @property {Array} [ipBuckets]
 * @property {Object} [jobs]
 * @property {Object} [lastAliasRequest]
 * @property {Object} [lastRollbackTarget]
 * @property {Array} [latestDeployments]
 * @property {string} [link]
 * @property {boolean} [live]
 * @property {*} [microfrontends]
 * @property {string} [name]
 * @property {string} [nodeVersion]
 * @property {Object} [oidcTokenConfig]
 * @property {Object} [optionsAllowlist]
 * @property {string} [outputDirectory]
 * @property {string} [passiveConnectConfigurationId]
 * @property {Object} [passport]
 * @property {Object} [passwordProtection]
 * @property {boolean} [paused]
 * @property {Object} [permissions]
 * @property {string} [previewDeploymentSuffix]
 * @property {boolean} [previewDeploymentsDisabled]
 * @property {boolean} [productionDeploymentsFastLane]
 * @property {boolean} [protectedSourcemaps]
 * @property {Object} [protectionBypass]
 * @property {Object} [protectionConfig]
 * @property {boolean} [publicSource]
 * @property {Object} [resourceConfig]
 * @property {Object} [rollbackDescription]
 * @property {Object} [rollingRelease]
 * @property {string} [rootDirectory]
 * @property {Object} [sandbox]
 * @property {Object} [security]
 * @property {string} [serverlessFunctionRegion]
 * @property {boolean} [serverlessFunctionZeroConfigFailover]
 * @property {Array} [services]
 * @property {Array} [skewProtectionAllowedDomains]
 * @property {number} [skewProtectionBoundaryAt]
 * @property {number} [skewProtectionMaxAge]
 * @property {boolean} [skipGitConnectDuringLink]
 * @property {boolean} [sourceFilesOutsideRootDirectory]
 * @property {Object} [speedInsights]
 * @property {Object} [ssoProtection]
 * @property {Object} [staticIps]
 * @property {Object} [targets]
 * @property {string} [tier]
 * @property {Object} [tracing]
 * @property {number} [transferCompletedAt]
 * @property {number} [transferStartedAt]
 * @property {string} [transferToAccountId]
 * @property {string} [transferredFromAccountId]
 * @property {*} [trustedIps]
 * @property {Object} [trustedSources]
 * @property {number} [updatedAt]
 * @property {Object} [usageStatus]
 * @property {boolean} [v0]
 * @property {boolean} [v0Created]
 * @property {Object} [webAnalytics]
 */

/**
 * @typedef {Object} ProjectRemoveMatch
 * @property {string} id
 * @property {string} [slug]
 * @property {string} [team_id]
 */

