// Generated by sdkgen go-cli target.
package main

import (
	"fmt"
	"strings"

	eng "github.com/boru-lang/boru/eng/go"
	sdk "github.com/voxgig-sdk/vercel-sdk/go"
)

// registerSDKWords installs three native boru words bound to the SDK:
// list / load / update. Each is declared with two overloads matching
// the signature  [query?:(Node or Scalar) entity:atom]:
//
//   [entity:Atom]            — no query (e.g. `list book`)
//   [query:Any entity:Atom]  — query is any Node or Scalar (e.g.
//                              `load {id:1} book`, `load 1 book`)
//
// The entity slot is /q-quoted so a bareword `book` parses as the
// Atom "book" rather than dispatching as an undefined word. Both
// overloads are all-forward (BarrierAllForward), so args are collected
// from the tokens following the word.
func registerSDKWords(r *eng.Registry, client *sdk.VercelSDK) {
	for _, op := range []string{"list", "load", "update"} {
		op := op
		single := eng.Signature{
			Args:      []*eng.Type{eng.TAtom},
			QuoteArgs: map[int]bool{0: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				return runOp(client, op, nil, args[0])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		dual := eng.Signature{
			Args:      []*eng.Type{eng.TAny, eng.TAtom},
			QuoteArgs: map[int]bool{1: true},
			Impl: eng.Go(func(args []eng.Value, _ map[string]eng.Value, _ []eng.Value, _ *eng.Registry) ([]eng.Value, error) {
				q := args[0]
				return runOp(client, op, &q, args[1])
			}),
			Returns:    []*eng.Type{eng.TAny},
			BarrierPos: eng.BarrierAllForward,
		}
		r.RegisterNativeFunc(eng.NativeFunc{
			Name:       op,
			Signatures: []eng.Signature{single, dual},
		})
	}
}

func runOp(client *sdk.VercelSDK, op string, query *eng.Value, entityAtom eng.Value) ([]eng.Value, error) {
	entityName, err := eng.AsAtom(entityAtom)
	if err != nil {
		return nil, fmt.Errorf("%s: entity argument is not an atom: %w", op, err)
	}
	ent, err := entityFor(client, entityName)
	if err != nil {
		return nil, fmt.Errorf("%s: %w", op, err)
	}

	var arg map[string]any
	if query != nil {
		arg, err = queryToMap(*query)
		if err != nil {
			return nil, fmt.Errorf("%s: %w", op, err)
		}
	}

	var result any
	switch op {
	case "list":
		result, err = ent.List(arg, nil)
	case "load":
		result, err = ent.Load(arg, nil)
	case "update":
		result, err = ent.Update(arg, nil)
	default:
		return nil, fmt.Errorf("unknown op %q", op)
	}
	if err != nil {
		return nil, err
	}
	return []eng.Value{eng.FromNative(extractData(result))}, nil
}

// entityFor dispatches on the lowercase entity name. The generator
// emits one `case "<name>":` per entity defined in the SDK model.
func entityFor(client *sdk.VercelSDK, name string) (sdk.VercelEntity, error) {
	switch strings.ToLower(name) {
	case "access_group":
		return client.AccessGroup(nil), nil
	case "ai_gateway":
		return client.AiGateway(nil), nil
	case "ai_gateway_rule":
		return client.AiGatewayRule(nil), nil
	case "ai_gateway_rule_list":
		return client.AiGatewayRuleList(nil), nil
	case "ai_gateway_virtual_model_config":
		return client.AiGatewayVirtualModelConfig(nil), nil
	case "ai_gateway_virtual_model_config_list":
		return client.AiGatewayVirtualModelConfigList(nil), nil
	case "alias":
		return client.Alias(nil), nil
	case "api_ai_gateway":
		return client.ApiAiGateway(nil), nil
	case "api_key":
		return client.ApiKey(nil), nil
	case "artifact":
		return client.Artifact(nil), nil
	case "authentication":
		return client.Authentication(nil), nil
	case "billing":
		return client.Billing(nil), nil
	case "bulk_redirect":
		return client.BulkRedirect(nil), nil
	case "cert":
		return client.Cert(nil), nil
	case "check":
		return client.Check(nil), nil
	case "checks_v2":
		return client.ChecksV2(nil), nil
	case "connect":
		return client.Connect(nil), nil
	case "connect_connector":
		return client.ConnectConnector(nil), nil
	case "connect_connector_list":
		return client.ConnectConnectorList(nil), nil
	case "connect_connector_project_connection_list":
		return client.ConnectConnectorProjectConnectionList(nil), nil
	case "connect_project_connection":
		return client.ConnectProjectConnection(nil), nil
	case "connect_project_connector_connection_list":
		return client.ConnectProjectConnectorConnectionList(nil), nil
	case "deployment":
		return client.Deployment(nil), nil
	case "dns":
		return client.Dns(nil), nil
	case "domain":
		return client.Domain(nil), nil
	case "domains_registrar":
		return client.DomainsRegistrar(nil), nil
	case "drain":
		return client.Drain(nil), nil
	case "edge_cache":
		return client.EdgeCache(nil), nil
	case "env":
		return client.Env(nil), nil
	case "environment":
		return client.Environment(nil), nil
	case "feature_flag":
		return client.FeatureFlag(nil), nil
	case "file":
		return client.File(nil), nil
	case "flag":
		return client.Flag(nil), nil
	case "flags_sdk_key_with_secret":
		return client.FlagsSdkKeyWithSecret(nil), nil
	case "global_config":
		return client.GlobalConfig(nil), nil
	case "global_config_item":
		return client.GlobalConfigItem(nil), nil
	case "global_config_token":
		return client.GlobalConfigToken(nil), nil
	case "integration":
		return client.Integration(nil), nil
	case "kms":
		return client.Kms(nil), nil
	case "list_event_type":
		return client.ListEventType(nil), nil
	case "log":
		return client.Log(nil), nil
	case "log_drain":
		return client.LogDrain(nil), nil
	case "marketplace":
		return client.Marketplace(nil), nil
	case "microfrontend":
		return client.Microfrontend(nil), nil
	case "network":
		return client.Network(nil), nil
	case "networking":
		return client.Networking(nil), nil
	case "observability":
		return client.Observability(nil), nil
	case "private_link_endpoint":
		return client.PrivateLinkEndpoint(nil), nil
	case "project":
		return client.Project(nil), nil
	case "project_member":
		return client.ProjectMember(nil), nil
	case "project_route":
		return client.ProjectRoute(nil), nil
	case "query":
		return client.Query(nil), nil
	case "record":
		return client.Record(nil), nil
	case "rolling_release":
		return client.RollingRelease(nil), nil
	case "sandbox":
		return client.Sandbox(nil), nil
	case "schema":
		return client.Schema(nil), nil
	case "security":
		return client.Security(nil), nil
	case "segment":
		return client.Segment(nil), nil
	case "storage":
		return client.Storage(nil), nil
	case "team":
		return client.Team(nil), nil
	case "tld_name":
		return client.TldName(nil), nil
	case "toggle":
		return client.Toggle(nil), nil
	case "user":
		return client.User(nil), nil
	case "vcr":
		return client.Vcr(nil), nil
	case "vcr_image_list":
		return client.VcrImageList(nil), nil
	case "vcr_repository_list":
		return client.VcrRepositoryList(nil), nil
	case "vcr_repository_permission_list":
		return client.VcrRepositoryPermissionList(nil), nil
	case "web_analytics":
		return client.WebAnalytics(nil), nil
	case "webhook":
		return client.Webhook(nil), nil

	}
	return nil, fmt.Errorf("unknown entity %q", name)
}

// queryToMap converts a boru Value (Map or Scalar) into the
// `map[string]any` shape the SDK expects. Maps are unwrapped via
// eng.ToNative. Scalars are wrapped as {"id": <value>} so the
// shorthand `load 1 book` becomes `load {id:1} book`.
func queryToMap(v eng.Value) (map[string]any, error) {
	if v.Parent.ConformsTo(eng.TMap) {
		m, ok := eng.ToNative(v).(map[string]any)
		if !ok {
			return nil, fmt.Errorf("query map could not be unwrapped")
		}
		return m, nil
	}
	if v.Parent.ConformsTo(eng.TScalar) {
		return map[string]any{"id": eng.ToNative(v)}, nil
	}
	return nil, fmt.Errorf("query must be a Map or Scalar, got %s", v.Parent)
}

// extractData walks an SDK result and replaces any sdk.Entity wrapper
// with the underlying record via .Data().
func extractData(x any) any {
	switch v := x.(type) {
	case sdk.Entity:
		return extractData(v.Data())
	case []any:
		out := make([]any, len(v))
		for i, e := range v {
			out[i] = extractData(e)
		}
		return out
	case map[string]any:
		out := make(map[string]any, len(v))
		for k, vv := range v {
			out[k] = extractData(vv)
		}
		return out
	}
	return x
}
